package uk.co.bitcat;

public class FilmPlotText {
    public static final String JURASSIC_PARK_PLOT = "Industrialist John Hammond and his bioengineering company, InGen, have created a theme park featuring cloned dinosaurs and prehistoric plants, called Jurassic Park, on Isla Nublar, a Costa Rican island. After one of the dinosaur handlers is killed by a Velociraptor, the park's investors, represented by lawyer Donald Gennaro, demand that experts visit the park and certify it is safe. To perform the certification inspections, Gennaro invites mathematician and chaos theorist Ian Malcolm, while Hammond invites paleontologist Dr. Alan Grant and paleobotanist Dr. Ellie Sattler. Upon arrival, the group is shocked to see a live Brachiosaurus.  " +
            "At the park's visitor center, the group learns that the cloning was accomplished by extracting dinosaur DNA from mosquitoes preserved in amber. DNA from frogs was used to fill in gaps in the dinosaurs' genome. To prevent breeding, all the dinosaurs were made female. Malcolm scoffs at the idea, saying that it will inevitably break down. The group witnesses the hatching of a baby Velociraptor and visits the raptor enclosure. During a luncheon, the group debates the ethics of cloning and the creation of the park, with Dr. Malcolm giving a harsh warning about the implications of genetic engineering in general.  " +
            "The group is then joined by Hammond's grandchildren, Lex and Tim Murphy, for a tour of the park, while Hammond oversees the tour from the park's control room. The tour does not go as planned, with most of the dinosaurs failing to appear and the group encountering a sick Triceratops. It is cut short as a tropical storm approaches Isla Nublar. Most of the park employees leave for the mainland on a boat while the visitors return to their electric tour vehicles, except Sattler, who stays behind with the park's veterinarian to study the Triceratops.  " +
            "Jurassic Park's lead computer programmer, Dennis Nedry, has been bribed by Dodgson, a man working for Hammond's corporate rival, to steal fertilized dinosaur embryos. Nedry deactivates the park's security system to gain access to the embryo storage room and stores the embryos inside a canister disguised as a shaving cream bottle. The power goes out, and the tour vehicles become stuck because of it. Most of the park's electric fences are deactivated as well, allowing the park's Tyrannosaurus rex to escape and attack the group. Grant, Lex, and Tim escape, while the Tyrannosaurus injures Malcolm and devours Gennaro. On his way to deliver the embryos to the island's docks, Nedry becomes lost in the rain, crashes his Jeep Wrangler, and is killed by a Dilophosaurus.  " +
            "Sattler helps the park's game warden, Robert Muldoon, search for survivors, but they only find Malcolm, just before the Tyrannosaurus returns. Grant, Tim, and Lex take shelter in a treetop. They later discover the broken shells of dinosaur eggs. Grant concludes that the dinosaurs have been breeding, which occurred because of their frog DNA—West African bullfrogs can change their sex in a single-sex environment, allowing the dinosaurs to do so as well, proving Malcolm right.  " +
            "Unable to decipher Nedry's code to reactivate the security system, Hammond and the park's chief engineer Ray Arnold reboot the park's system. The group shuts down the park's grid and retreats to an emergency bunker, while Arnold heads to a maintenance shed to complete the rebooting process. When Arnold fails to return, Sattler and Muldoon head to the shed. They discover the shutdown has deactivated the remaining fences and released the Velociraptors. Muldoon distracts the raptors, while Sattler goes to turn the power back on, before being attacked by a raptor and discovering Arnold's severed arm. Meanwhile, Muldoon is caught off guard and killed by the other two raptors.  " +
            "Grant, Tim, and Lex reach the visitor center. Grant heads out to look for Sattler, leaving Tim and Lex inside. Tim and Lex are pursued by the raptors in an industrial kitchen, but the children escape and join Grant and Sattler. Lex restores full power from the control room, allowing them to call Hammond, who in turn calls for help. Grant, Tim, Lex, and Sattler are cornered by the raptors, but they escape when the Tyrannosaurus suddenly appears and kills the raptors. Hammond arrives in a jeep with Malcolm, and all of the survivors board a helicopter to leave the island.";
}